spring.application.name=main-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#Spring JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/MainDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.sql=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${smtp.username}
spring.mail.password=${smtp.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=aappaa
spring.rabbitmq.password=aappaapass
#App
app.roles.default-admin-name=Admin
#In milliseconds
app.ampq.organisation-user-sync-roles.queue.ttl=900000