spring.application.name=main-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Spring JPA
spring.datasource.url=jdbc:postgresql://${main.datasource.host}:${main.datasource.port}/${main.datasource.database}
spring.datasource.username=${main.datasource.username}
spring.datasource.password=${main.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
app.clients.auth-service.name=auth-service
app.clients.file-service.name=file-service
logging.level.com.crm.main=DEBUG
logging.level.sql=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#RabbitMQ
spring.rabbitmq.host=${rabbit.host}
spring.rabbitmq.port=${rabbit.port}
spring.rabbitmq.username=${rabbit.username}
spring.rabbitmq.password=${rabbit.password}
#App
app.roles.default-admin-name=Admin
app.roles.default-member-name=Member
app.files.default-root-dir-prefix-name=Root
#In milliseconds
app.ampq.organisation-user-sync-roles.queue.ttl=900000
#In seconds. 3 days.
app.invitation.expiration-time=259200