spring.application.name=main-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Spring JPA
spring.datasource.url=jdbc:postgresql://${main.datasource.host}:${main.datasource.port}/${main.datasource.database}
spring.datasource.username=${main.datasource.username}
spring.datasource.password=${main.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.com.crm.main=DEBUG
logging.level.sql=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${smtp.username}
spring.mail.password=${smtp.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#RabbitMQ
spring.rabbitmq.host=${rabbit.host}
spring.rabbitmq.port=${rabbit.port}
spring.rabbitmq.username=${rabbit.username}
spring.rabbitmq.password=${rabbit.password}
#App
app.roles.default-admin-name=Admin
app.roles.default-member-name=Member
#In milliseconds
app.ampq.organisation-user-sync-roles.queue.ttl=900000
#In seconds. 3 days.
app.invitation.expiration-time=259200
app.frontend.url=${main.frontend.url}